# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=64)),
                ('email', models.CharField(default='', max_length=128, null=True)),
                ('website', models.CharField(default=None, max_length=256, null=True)),
                ('meeting_times', models.CharField(default=None, max_length=256, null=True)),
                ('president', models.IntegerField(null=True)),
                ('treasurer', models.IntegerField(null=True)),
                ('icc_rep', models.IntegerField(null=True)),
            ],
            options={
                'permissions': (('edit_club', 'Can edit the club information'),),
            },
        ),
    ]
