# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='meeting_times',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='website',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
