# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectx', '0002_auto_20170102_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubs',
            options={},
        ),
    ]
