# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectx', '0003_auto_20170102_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='email',
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='clubs',
            name='website',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
