# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectx', '0004_auto_20170104_2316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clubs',
            new_name='Club',
        ),
    ]
